# Generated by Django 4.1.5 on 2023-01-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=150)),
                ('Massege', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='OurRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='ImageRoom')),
                ('Name', models.CharField(max_length=150)),
                ('Price', models.CharField(max_length=150)),
                ('discount_price', models.CharField(max_length=150)),
                ('Day', models.CharField(max_length=150)),
                ('Room_Discription', models.CharField(max_length=500)),
                ('Distance', models.CharField(blank=True, max_length=150, null=True)),
                ('Catagory', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'OurRoom',
                'verbose_name_plural': 'OurRooms',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ImageTeam')),
                ('name', models.CharField(max_length=150)),
                ('roll', models.CharField(max_length=150)),
                ('shift', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Team Meamber',
                'verbose_name_plural': 'Team Meamber',
            },
        ),
    ]
