# Generated by Django 4.1.5 on 2023-01-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourroom',
            name='discount_price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
