# Generated by Django 4.1.5 on 2023-01-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_ourroom_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('birthday', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('nid', models.CharField(max_length=150)),
                ('st_date', models.CharField(max_length=150)),
                ('end_date', models.CharField(max_length=150)),
                ('topics', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'RoomOrder',
                'verbose_name_plural': 'RoomOrders',
            },
        ),
    ]
