# Generated by Django 4.1.5 on 2023-01-19 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_roomorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomorder',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='roomorder',
            name='topics',
        ),
    ]
